clang-tidy: range for loop conversions
Exiv2/exiv2 pull request #1596
Opened 2021-04-29 06:43 UTC by neheb

Found with modernize-loop-convert

Ran through git clang-format.

Also removed several questionable loops and replaced with simpler
algorithms.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

2021-04-29 08:46 UTC, neheb commented on src/epsimage.cpp
> +                if (memcmp(buf.pData_, eps.data(), eps.size()) == 0) {
Interestingly enough std::any_of or std::find can't be used here. No idea why.

2021-04-29 09:04 UTC, hassec requested changes

2021-04-29 09:45 UTC, neheb commented on samples/easyaccess-test.cpp
> +    for (auto&& easyAcces : easyAccess) {
The name was automated. Will change.

2021-04-29 09:46 UTC, neheb commented on samples/exifdata.cpp
> +    return std::distance(exifData.begin(), exifData.end());
Sounds right.

2021-05-03 07:21 UTC, piponazo approved these changes, later dismissed
LGTM, thanks for this nice contribution!

Could you please rebase your branch in top of `main`? It looks like there are some compiler errors on the appveyor builds.

2021-05-03 09:06 UTC, neheb commented
Rebased.

2021-05-03 10:56 UTC, piponazo approved these changes

2021-05-03 12:50 UTC, merged