Initialize field.
Exiv2/exiv2 pull request #1606
Opened 2021-05-07 20:51 UTC by kevinbackhouse

Uninitialized field was triggering a UBSAN failure. I believe it was harmless because the field gets overwritten with a correct value before it is used.

2021-05-08 10:57 UTC, hassec approved these changes
LGTM :+1:

2021-05-09 15:36 UTC, piponazo requested changes

2021-05-09 15:36 UTC, piponazo commented on src/actions.hpp
> +        bool binary_ = false;
This cannot be done with c++98/03, the travis-ci builds are complaining about it appropriately:

```bash
/home/travis/build/Exiv2/exiv2/src/actions.hpp:95:24: error: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [-Werror]
         bool binary_ = false;
```
Therefore, you will need to initialise this variable in the constructor initialisation list

2021-05-09 16:18 UTC, piponazo commented
I have assigned to this PR the label `forward-to-main` so that we can test the changes proposed in https://github.com/Exiv2/exiv2/pull/1616

2021-05-10 05:21 UTC, piponazo approved these changes

2021-05-10 08:56 UTC, kevinbackhouse commented
@piponazo: Do you know what's going on with the Travis CI error? It looks to me like a package installation error related to valgrind, rather anything specifically caused by this change.

2021-05-10 09:34 UTC, piponazo commented
> @piponazo: Do you know what's going on with the Travis CI error? It looks to me like a package installation error related to valgrind, rather anything specifically caused by this change.

I fixed that issue only on `main` (https://github.com/Exiv2/exiv2/pull/1599). It was a problem with the travis-ci images. I will backport that fix to 0.27-maintenance this evening so that we have a green CI for 0.27 too.

2021-05-10 11:45 UTC, merged