constexpr and member init changes.
Exiv2/exiv2 pull request #1659
Opened 2021-05-17 08:00 UTC by neheb

2021-05-17 12:18 UTC, piponazo requested changes
Thanks @neheb for your work.

As commented in previous PRs, let's be conservative about formatting changes at the moment (until we have a discussion about the clang-formatting options). If you remove the big formatting changes in the static tables, I will be happy to approve and merge the changes proposed here.

2021-05-17 12:18 UTC, piponazo commented on src/datasets.cpp
> +        {IptcDataSets::ModelVersion, "ModelVersion", N_("Model Version"),
Could you please revert the formatting changes here and just keep the 1-line change about `static constexpr` ?

2021-05-17 12:18 UTC, piponazo commented on src/datasets.cpp
> +    static constexpr DataSet application2Record[] = {
Could you please revert the formatting changes here and just keep the 1-line change about `static constexpr` ?

2021-05-17 12:18 UTC, piponazo commented on src/properties.cpp
> +    static constexpr XmpNsInfo xmpNsInfo[] = {
Could you please revert the formatting changes here and just keep the 1-line change about `static constexpr` ?

2021-05-18 01:19 UTC, neheb commented
Annoying.

I'm adding [[gnu::unused]] which according to the standard, is allowed to be present even if the compiler does not support it.

This should not be an error under WIndows.

2021-05-18 06:37 UTC, piponazo approved these changes, later dismissed
Thanks for your endless efforts in modernizing the codebase! 💪

2021-05-18 12:24 UTC, piponazo approved these changes, later dismissed

2021-05-19 09:44 UTC, piponazo approved these changes

2021-05-19 12:11 UTC, merged