Show the Appveyor badge corresponding to the master branch
Exiv2/exiv2 pull request #197
Opened 2017-12-17 21:20 UTC by piponazo

I recently noticed that we were not shoring the right badge in the main page of the project. This PR should fix the situation.

2017-12-17 21:27 UTC, D4N requested changes
Can you correct the speling of the commit message from budget to badge?

2017-12-17 21:32 UTC, piponazo commented
Ouch, it seems that at Sunday nights my mind does not work very well 😅.
Sure, I will change it.

El 17 dic. 2017 22:27, "D4N" <notifications@github.com> escribió:

> *@D4N* requested changes on this pull request.
>
> Can you correct the speling of the commit message from budget to badge?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Exiv2/exiv2/pull/197#pullrequestreview-84011679>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAGQ9QNFWs2TbBO5cLvVFB8m5-viIb3Aks5tBYc6gaJpZM4REzMK>
> .
>

2017-12-19 08:27 UTC, D4N approved these changes

2017-12-19 08:28 UTC, D4N commented
Can you please rebase your changes before merging?

2017-12-19 13:40 UTC, tbeu approved these changes

2017-12-19 14:52 UTC, piponazo commented
Yes, I do not know since when, but now github shows to me a nice "Rebase and merge" button 😃

2017-12-19 14:53 UTC, merged