[nikon] Add Tokina ATX-i 11-20mm F2.8 CF lens
Exiv2/exiv2 pull request #2072
Opened 2022-02-04 23:13 UTC by Sturmflut

Test data from lensfun/lensfun#1255

2022-02-05 07:10 UTC, piponazo commented
Hum ... weird, seems to be working on windows platforms but failing on Mac/Linux. Any idea why this might be happening?

2022-02-05 09:52 UTC, piponazo requested changes

2022-02-05 09:52 UTC, piponazo commented on tests/bugfixes/github/test_pr_2072.py
> +    filename = "$data_path/Sigma_APO_MACRO_180_F3.5_EX_DG_HSM.exv"
There seems to be a copy/paste typo here. You are using a different file than the one added in this PR (also in the test name)

2022-02-06 16:45 UTC, hassec commented on tests/bugfixes/github/test_pr_2072.py
> +]
Could you try the below? 

```suggestion
    stdout = ["Exif.NikonLd3.LensIDNumber                   Byte        1  Tokina ATX-i 11-20mm F2.8 CF\n"]
```

2022-02-08 19:32 UTC, Sturmflut commented
Fixed the test

2022-02-08 21:58 UTC, piponazo submitted a review, later dismissed

2022-02-09 16:41 UTC, piponazo approved these changes

2022-02-09 16:41 UTC, merged