mostly clang-tidy cleanups
Exiv2/exiv2 pull request #2124
Opened 2022-03-04 09:17 UTC by neheb

2022-03-04 12:05 UTC, piponazo requested changes
Thanks for the contribution! I just made some minor comments here and there, but most of the changes look good to me :wink:

2022-03-04 14:02 UTC, neheb commented on src/basicio.cpp
> +        byte* pMappedArea_{};    //!< Pointer to the memory-mapped area
bool gets initialized to 0, which is false. Pointers gets initialized to nullptr. Note that smart pointers get default initialized to nullptr.

2022-03-04 14:04 UTC, neheb commented on src/preview.cpp
> +            return {data + nativePreview_.position_, static_cast<size_t>(static_cast<long>(nativePreview_.size_))};
clang-tidy did this automatically. I'll fix it manually.

2022-03-04 14:08 UTC, neheb commented on src/preview.cpp
> +            return {data + nativePreview_.position_, static_cast<size_t>(static_cast<long>(nativePreview_.size_))};
Oh this may have been a bugfix. {} does not allow implicit conversions, hence the cast.

2022-03-04 23:55 UTC, neheb commented
That should be it.

2022-03-05 08:57 UTC, piponazo approved these changes
LGTM, Thanks!

2022-03-05 08:57 UTC, merged