[0.26] Backport fixes for CVE-2017-17725 and CVE 2017-17669
Exiv2/exiv2 pull request #232
Opened 2018-02-17 00:01 UTC by a17r

2018-02-17 10:56 UTC, clanmills commented
This looks like a very useful and valuable PR.  I'm wondering how best to integrate this with the code base.  Should we apply this (and possibly other fixes) and call it 0.26.1?

2018-02-19 23:09 UTC, D4N requested changes
Please cherry-pick 2e745b0b and 27d7a5d9, too otherwise dc3cb71cbb92f839ba5479d42ff0249e040a152b is not really useful (those two commits add the test suite to the repo & to travis).

Nevertheless, thanks for taking the time to backport these changes.

2018-02-19 23:12 UTC, D4N commented
@clanmills I think this should just go into the 0.26 branch without a new release, as the API stayed the same. The 0.26 branch is mostly just an accumulation of backported patches from master to help downstream package maintainers.

2018-02-19 23:17 UTC, a17r commented
@D4N appveyor.yml does not exist in 0.26 branch.

I'm confused, wasn't there plans to do a 0.26 point release? The number of security fixes certainly would justify it, and there should be more to come still. A snapshot can only ever be a last resort if there is no release available.

2018-02-19 23:25 UTC, D4N commented
@a17r Feel free to drop the part of 27d7a5d968434dee2ec5bd0fd208cff16265689d that contains the changes for Appveyor.

Concerning the dot-release, now that you say it, I think there were plans. But to be honest there are still lots of unfixed issues that probably concern 0.26 too. So doing a dot-release now might be a bit too early. What do you think @clanmills (I have little experience with releases)?

2018-02-19 23:50 UTC, D4N commented
@a17r Could you also cherry-pick 78c55947, eb33dcd9, and 307138c12c9e09d9bb1a7d9bf89195d9d4d9d7c7? And apply this patch:
``` diff
--- a/.travis/install.sh
+++ b/.travis/install.sh
@@ -7,6 +7,6 @@ if [[ "$(uname -s)" == 'Linux' ]]; then
     sudo pip install virtualenv
 else
     brew update
-    brew install gettext libssh expat zlib curl
+    brew install gettext libssh expat zlib curl python3
     # By default it already has cmake 3.6.2
 fi
```
I hope that fixes the travis build on MacOSX.

Sorry that this is becoming a mess.

2018-02-20 00:05 UTC, a17r commented
@D4N Thanks for your guidance, hope I got it right.

2018-02-20 22:24 UTC, D4N commented
Oh, boy, the build is still broken. This is going to be a little more complicated.

I hope with the following steps it will be fixed:
- drop the changes to `test/bugfixes-test.sh` that 138c7fa13fcc3e57e61ec32f4d3321f40a452d65 made (this uses the old test suite, that is a pita for backporting & that we don't want to touch anymore)
- cherry-pick e0ab5aaa87322808274eb265f4ab1d2b35ec5a85
- do a `touch tests/bugfixes/__init__.py` and `touch tests/bugfixes/github/__init__.py` (you can cherry-pick these changes from 085c9715fc6bf2251e4273da4c18fede22e7eaa9, but that commit also adds a lot of additional test files, that you don't want)
- add the following file to `tests/bugfixes/github/` as `test_CVE_2017_17725.py` (this is from a WIP branch and the commit that adds it gets rebased on every push to master, so no cherry-picking is possible here, sorry):
```Python
# -*- coding: utf-8 -*-

import system_tests


class TestCvePoC(system_tests.Case):

    url = "https://github.com/Exiv2/exiv2/issues/188"
    found_by = ["Wei You", "@youwei1988"]

    filename = "{data_path}/poc_2017-12-12_issue188"
    commands = ["{exiv2} " + filename]
    stdout = [""]
    stderr = ["""std::overflow_error exception in print action for file """ + filename + """:
Overflow in addition
"""]
    retval = [1]
```
- apply the following patch:
``` diff
--- a/.travis/install.sh
+++ b/.travis/install.sh
@@ -3,7 +3,7 @@ set -e # Enables cheking of return values from each command
 set -x # Prints every command
 
 if [[ "$(uname -s)" == 'Linux' ]]; then
-    sudo apt-get install cmake zlib1g-dev libssh-dev gettext expat libcurl4-openssl-dev
+    sudo apt-get install cmake zlib1g-dev libssh-dev gettext expat libcurl4-openssl-dev libxml2-utils
     sudo pip install virtualenv
 else
     brew update
```

I hope that fixes the build.

2018-02-22 19:38 UTC, a17r commented
Hmm still no luck. Now, we've both put our time in that PR already but I can see where reluctance to continue on 0.26 branch may come from.

2018-02-27 10:55 UTC, a17r commented
> I think we should create a policy what should be backported and what not to prevent these problems (and possibly automate the process, afaik some projects have bots that backport patches for them).

A git workflow policy certainly would help. Usually I would expect fixes to go into the stable branch first, and merged forward to master afterwards. Cherry-picking only happening for older stable branches that still receive support but have diverged too much.

I don't think a bot would be able to fix the situation exiv2 is in right now. There have been just too many changes to master already, but that is surely going to settle with a future 0.28 being able to focus more on feature development rather than infrastructure.

2018-02-27 11:43 UTC, clanmills commented
I agree.  I would like to bring more stability to Exiv2.  However, I'm new to Git/GitHub and have found it almost impossible to use the system.  Hostile reviews of my submissions have eliminated my willingness to change code.  I've been effectively frozen out of the project since last September.

I've offered to host a team meeting at my home in England on May 5 with the aim of uniting the team in a shared goal and strong cooperation.  Nobody has accepted the invitation.  https://github.com/Exiv2/exiv2/issues/225

While I wait for matters concerning the code to improve, I have been busy dealing with users on Redmine forum/issues.  Recently, I've successfully recruited a couple of new volunteers.  http://dev.exiv2.org/projects/exiv2/boards  

The move from SVN to GitHub has resulted in recruiting two new active contributors:  @D4N and @piponazo and several other occassional contributors.  However this change has also locked me out of the code base and left me unable to contribute.  Very frustrating.

If you know how to rectify and improve this situation, I assure you of my enthusiastic cooperation.

2018-02-28 13:42 UTC, clanmills commented
I apologise to both @D4N and @piponazo for my statement _"hostile reviews"_.   I’ve allowed my frustration with git/github to appear to be criticism of other team members.  That’s not the case.  I admire their insights into the code and appreciate their reviews.

@D4N has confirmed that he will come to the Team Meeting in May and I am delighted about that.  I hope @piponazo and others will join us.

2018-03-19 22:48 UTC, D4N approved these changes

2018-03-19 22:48 UTC, merged

2018-03-19 22:49 UTC, D4N commented
@a17r I totally missed that you pushed additional commits and fixed the build. Thanks a lot for your endurance!