Update README.md wrt BMFF
Exiv2/exiv2 pull request #2405
Opened 2022-11-01 15:44 UTC by postscript-dev

Suggested during discussion in https://github.com/Exiv2/exiv2/issues/2398.

2022-11-01 15:48 UTC, 1div0 requested changes
I would use full name JPEG XL instead of the abreviation.

2022-11-01 15:53 UTC, kmilos commented on README.md
> +    - [Support for bmff files (e.g., AVIF, CR3, HEIF, HEIC, and JXL)](#BMFF)
No comma after "e.g."?

2022-11-01 15:53 UTC, kmilos commented on README.md
> +## Support for bmff files (e.g., AVIF, CR3, HEIF, HEIC, and JXL)
Ditto?

2022-11-02 19:31 UTC, postscript-dev commented
@1div0 
> I would use full name JPEG XL instead of the abbreviation.

I have made the change and will try and use the full name in the future.

2022-11-02 20:26 UTC, kmilos approved these changes

2022-11-03 06:39 UTC, 1div0 approved these changes

2022-11-03 08:00 UTC, merged