Remove libinih from codebase and add it as a dependency instead
Exiv2/exiv2 pull request #2443
Opened 2022-12-27 15:03 UTC by kevinbackhouse

Fixes: #1811 

`ini.cpp` and `ini.hpp` are copied from this repo: https://github.com/benhoyt/inih. Most platforms have a `libinih-dev` library that we can add as a dependency, so we can remove `ini.cpp` and `ini.hpp` from the exiv2 codebase.

On most platforms, it is easy to replace `ini.cpp` and `ini.hpp` with a dependency, but some platforms only have a `libinih` library and not a `libinih-devel` library, which is insufficient for building exiv2. On those platforms, I had to update the Actions workflows to build inih from source. This is the list of platforms where I had to do that:

1. Centos Stream
2. MSYS2
3. Cygwin

2022-12-27 15:28 UTC, kmilos commented
Et voila for MSYS2: https://github.com/msys2/MINGW-packages/pull/14781

2022-12-27 15:37 UTC, kevinbackhouse commented
> Et voila for MSYS2: [msys2/MINGW-packages#14781](https://github.com/msys2/MINGW-packages/pull/14781)

Wow, that was fast! I was looking into it and only just found that repo about a minute ago!

2022-12-27 15:51 UTC, kevinbackhouse commented
I'll convert this PR to draft until https://github.com/msys2/MINGW-packages/pull/14781 is ready.

The build failure in CIFuzz should resolve itself automatically after this PR is merged, because OSS-Fuzz uses the install script from our main branch: https://github.com/google/oss-fuzz/blob/582e69cebf7a970faf4ffb0c5492e497d860cb12/projects/exiv2/Dockerfile#L19

2022-12-27 16:45 UTC, kmilos commented
@kevinbackhouse Merged. It might take a couple of hours/days until the binary package actually trickles down to the repo...

2022-12-28 15:38 UTC, kmilos commented on .github/workflows/on_PR_windows_matrix.yml
> +            git
git no longer needed for MSYS2 jobs

2022-12-28 15:44 UTC, kevinbackhouse commented on .github/workflows/on_PR_windows_matrix.yml
> +            git
```suggestion
```

2022-12-29 14:52 UTC, kevinbackhouse commented
@piponazo: do these cmake/conan changes look ok to you?

2022-12-29 16:01 UTC, piponazo requested changes
It seems to me that libinih is a strong dependency and we should be more strict in checking that the dependency is properly found.

Apart from that, all the changes look good to me 👏

2022-12-29 16:01 UTC, piponazo commented on src/CMakeLists.txt
> +if( inih_FOUND )
(related to previous comment) If the library is required we should check in the file `cmake/findDependencies.cmake` if the library is not found and fail. Afterwards, here we could remove the conditional.

2022-12-29 19:04 UTC, kevinbackhouse commented on cmake/findDependencies.cmake
> +if( inih_FOUND )
Good idea! This is done now.

2023-01-02 16:43 UTC, piponazo approved these changes
LGTM! Thanks ❤️

2023-01-04 10:44 UTC, merged

2023-01-05 12:33 UTC, kmilos commented
FWIW: https://cygwin.com/pipermail/cygwin/2023-January/252780.html (couldn't find any other channel for such requests...)

2023-01-05 21:23 UTC, kmilos commented
There is follow-up re Cygwin: https://cygwin.com/pipermail/cygwin/2023-January/252781.html

Anyone able to test?

2023-01-06 08:27 UTC, hassec commented
@kevinbackhouse This seems to have broken the [nighlty release build](https://github.com/Exiv2/exiv2/actions/runs/3852674209/jobs/6565003830)

2023-01-06 09:33 UTC, kevinbackhouse commented
> @kevinbackhouse This seems to have broken the [nighlty release build](https://github.com/Exiv2/exiv2/actions/runs/3852674209/jobs/6565003830)

@hassec: sorry about that! I'll look into it.

2023-01-12 05:31 UTC, eddiezato commented
I build statically with msys2/ucrt64 to get one exe. Now `exiv2.exe` asks for `libINIReader.dll` and I can't solve it with `-linih` or `-linireader`. Any help, please?

2023-01-12 08:22 UTC, kmilos commented
> I build statically with msys2/ucrt64 to get one exe. Now `exiv2.exe` asks for `libINIReader.dll`

Yep, the MSYS2 package did not ship the static library in the default build options... An update should hit the repo in a couple of days.

2023-07-24 15:39 UTC, kmilos commented
> On `alpine`, if you install `inih-dev` without `inih-inireader-dev`, you get that error.

Granted, this was not envisaged when I wrote the module. I briefly checked the "major" distros these are usually packaged together...

2023-07-24 15:41 UTC, Ryanf55 commented
> inih_inireader_NOTFOUND

On alpine, they are separate installs, seems like a quick one-liner could fix it.