Add option to disable tools (currently exiv2 binary)
Exiv2/exiv2 pull request #32
Opened 2017-08-20 20:52 UTC by a17r

In a multiarch build, one may want to build binaries only for native arch.

2017-08-20 22:12 UTC, piponazo commented
I think it is a good idea to add this variable to disable the generation of the apps. I would even control with that variable the generation of the samples.

I think many developers might be only interested in the usage of the libraries and they might not be interested at all in compiling the applications.

If @clanmills agrees, I will propose you some ideas to improve this Pull Request.

2017-08-20 22:25 UTC, a17r commented
Yes I thought about samples as well and ignored it for now - it is unfortunate that a subdirectory labelled 'unit tests' is installing stuff at all - and is seemingly also required to generate doc.

2017-08-21 15:13 UTC, clanmills commented
With the autotools build, the default build is the library + about 10 little programs usesd by the test suite: exiv2/exifprint/addmoddel/etc..  $ make samples builds the other samples.

I believe the CMake build defaults to building the libraries + exiv2 + samples + test programs.  Perhaps well could polish this to be:

1 default builds = library + exiv2 application
2 option to omit exiv2 application
3 we bring the test programs up-to-date when we run the test suite
4 option to build everything (library + exiv2, test programs and samples)

However I don't have any strong feelings about this.  The library is about 75000 lines of C++.  The samples and test programs are small (10000 lines of C++). 

What is _**"unit tests"**_?

2017-08-21 15:19 UTC, a17r commented
Took that from

``OPTION( EXIV2_ENABLE_BUILD_SAMPLES "Build the unit tests" ON )``

2017-08-21 18:12 UTC, piponazo requested changes

2017-08-21 18:13 UTC, merged

2017-08-21 18:27 UTC, clanmills commented on src/CMakeLists.txt
> +if(EXIV2_ENABLE_TOOLS)
You have the correct idea in reorganizing the code.  We really should have src/ for the library code (test/src=test applications) and samples/src for sample applications.  However, this is lots of messing about.  Your thoughts involving  `if (EXIV2_ENABLE_TOOLS)` is the quick fix.

I'm got a couple of other things to suggest:
1) It should be called EXIV2_ENABLE_BUILD_EXIV2APP "Build exiv2 command line program"
2) The help string for EXIV2_ENABLE_BUILD_SAMPLES "Build sample applications"