Deprecated removal
Exiv2/exiv2 pull request #694
Opened 2019-02-08 19:20 UTC by Kicer86

Fix for #675

2019-02-08 21:42 UTC, piponazo commented
There is one test failing on the Mac jobs:

```
======================================================================
FAIL: test_run (bugfixes.redmine.test_issue_836.WriteMetadataDestroysResourceForkOnMacOSXForBigFiles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/Exiv2/exiv2/tests/system_tests.py", line 632, in test_run
    self.compare_stderr(i, command, processed_stderr, stderr)
  File "/Users/travis/build/Exiv2/exiv2/tests/system_tests.py", line 755, in compare_stderr
    msg="Standard error does not match"
  File "/Users/travis/build/Exiv2/exiv2/tests/system_tests.py", line 726, in _compare_output
    expected, got, msg=msg
AssertionError: 'Exiv2 exception in modify action for file[177 chars]pe\n' != ''
- Exiv2 exception in modify action for file /Users/travis/build/Exiv2/exiv2/test/data/exiv2-bug836_copy.eps:
- /Users/travis/build/Exiv2/exiv2/test/data/exiv2-bug836_copy.eps: The file contains data of an unknown image type
 : Standard error does not match
```
I guess that test needs to be also removed after removing the EPS image code.

2019-02-09 07:43 UTC, Kicer86 commented
Yeah, I've been looking at it. I'll try to fix it today.

2019-02-10 13:18 UTC, piponazo requested changes

2019-02-10 13:18 UTC, piponazo commented on CMakeLists.txt
> -option( EXIV2_ENABLE_VIDEO            "Build video support into library"                      OFF )
There are two more occurrences of that variable in the code. Could you take care of removing them?

```
cmake/printSummary.cmake
49:OptionOutput( "Building video support:             " EXIV2_ENABLE_VIDEO              )

cmake/packaging.cmake
56:if ( EXIV2_ENABLE_VIDEO )
```

2019-02-10 13:18 UTC, piponazo commented on CMakeLists.txt
> -option( EXIV2_ENABLE_SSH              "USE Libssh for SshIo (WEBREADY)"                       OFF )
There are many other occurrences of that variable in the CMake code and documentation. Could you remove the rest of them?

```
14:16 $ ag EXIV2_ENABLE_SSH
README-CONAN.md
608:$ cmake -DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_ENABLE_CURL=ON -DEXIV2_ENABLE_SSH=ON ..

cmake/generateConfigFile.cmake
6:    set(EXV_USE_SSH   ${EXIV2_ENABLE_SSH})

cmake/printSummary.cmake
53:    OptionOutput( "USE Libssh for SshIo:               " EXIV2_ENABLE_SSH            )

cmake/findDependencies.cmake
22:    if( EXIV2_ENABLE_SSH )

src/CMakeLists.txt
110:    if( EXIV2_ENABLE_SSH )
170:    if( EXIV2_ENABLE_SSH )

CMakeLists.txt
23:option( EXIV2_ENABLE_SSH              "USE Libssh for SshIo (WEBREADY)"                       OFF )
```

2019-02-10 17:09 UTC, piponazo approved these changes

2019-02-10 22:47 UTC, merged

2019-02-11 18:43 UTC, Kicer86 commented
@piponazo  after @tbeu 's commits it is clean now.