Enable support for msvc 2015
Exiv2/exiv2 pull request #751
Opened 2019-03-19 07:11 UTC by piponazo

This minor change will enable back the support for msvc 2015.

I will also add another job in Appveyor to check that we do not break that. However, I wanted to check first that it is not breaking anything else.

2019-03-19 12:08 UTC, tbeu requested changes
Please comment with `#if defined(_MSC_VER) && _MSC_VER < 1910`.

2019-03-20 20:47 UTC, piponazo commented
> Please comment with #if defined(_MSC_VER) && _MSC_VER < 1910.

It is actually needed for Linux and Mac, and not needed on MSVC. On VS2017 it is accepted but on MSVC2015 it produces this error:

```
..\src\crwimage_int.cpp(155): error C2373: 'signature_': redefinition; different type modifiers
d:\dev\windows\projects\exiv2\src\crwimage_int.hpp(517): note: see declaration of 'signature_'
```

2019-03-21 21:54 UTC, D4N commented
> > Please comment with #if defined(_MSC_VER) && _MSC_VER < 1910.
> 
> It is actually needed for Linux and Mac, and not needed on MSVC. On VS2017 it is accepted but on MSVC2015 it produces this error:
> 
> ```
> ..\src\crwimage_int.cpp(155): error C2373: 'signature_': redefinition; different type modifiers
> d:\dev\windows\projects\exiv2\src\crwimage_int.hpp(517): note: see declaration of 'signature_'
> ```

That's an odd error, given the types being the same.

2019-03-21 21:55 UTC, D4N reviewed
I have no objections to this change, as it doesn't break the builds. But someone with more Windows knowledge should give the final ok.

2019-03-22 06:42 UTC, piponazo commented
>  But someone with more Windows knowledge should give the final ok.

What I can do is to add back an AppVeyor build for MSVC2015. I do not think we need a "Windows Expert" here, but just a compiler check turning into GREEN or RED 😇 

Note that I have tested these changes on Windows with both compilers.

2019-03-22 08:42 UTC, D4N commented
> > But someone with more Windows knowledge should give the final ok.
> 
> What I can do is to add back an AppVeyor build for MSVC2015. I do not think we need a "Windows Expert" here, but just a compiler check turning into GREEN or RED
> 
> Note that I have tested these changes on Windows with both compilers.

If it's not too much work, please add MSVC 2015, as that was the plan anyway? If this is blocking something else, we can merge this now.

2019-03-25 17:02 UTC, piponazo commented
Damn it, it is more difficult that I thought to add back the MSVC 2015 to AppVeyor. 

Let's merge this now, just so that I can work on Exiv2 with MSVC2015 when I am in a computer with such compiler and I'll try to add back a build for MSVC2015 in Appveyor when I find some more time.

2019-03-25 17:03 UTC, merged