Changes for v0.27.1
Exiv2/exiv2 pull request #782
Opened 2019-04-18 09:21 UTC by clanmills

Gentlemen:

I hope this is v0.27.1.  I haven't had any feedback from users.

I've added support for Visual Studio 2019 and updated README.md concerning an issue with the MinGW/Source build.  I've retained the fix for #744 which was submitted to v0.27-maintenance.  And I've reviewed/revised releasenotes.txt, README.md and README-CONAN.md 

I hope this is good to go.  I'm sure you'll spot more changes.

When it's good, could you tag this as "v0.27.1".  Then I'll get Jenkins to build.  I'll test the builds and publish on https://exiv2.org

Let me know if you'd like to have a meeting (1 hour on-line) to talk together.  I hope to do "v0.27.2 RC1" by 2019-06-15 and v0.27.2 by 2019-06-30.

2019-04-18 15:14 UTC, D4N requested changes
If we intend to support Visual Studio 2019, then we **must** add a CI job for Appveyor to it.

And don't we still support VS 2010 & 2013 for 0.27?

2019-04-18 16:33 UTC, clanmills commented
Yes, we still support other versions of Visual Studio, however I've made them less prominent.  I believe 2008 etc build, however I don't want to say they are actively supported.  I've removed 2008/10/12/13 from both the MacMini and my laptop.  

I don't know that you need to add a CI/2019 job at the moment.  I've tested the Source build on both the MacMini and my laptop.  So, the source bundle builds and that's what's being released.

You can add a CI 2019 job to the 'master' branch if you wish.  Or you can leave that to @nehaljwani  and I to organise using Jenkins.

2019-04-18 17:50 UTC, piponazo commented
> If we intend to support Visual Studio 2019, then we must add a CI job for Appveyor to it.

It is not available yet on Appveyor. I guess they will provide a windows image with VS2019 once the final version is released. 

All the changes look good to me except removing the mentions to old versions of Visual Studio. If there is something important to know about Exiv2 0.27 and future versions of it, is that Exiv2 0.27 is C++98 while in master we moved to c++11. I think we should keep those mentions in 0.27 and we can remove them from master.

2019-04-18 19:41 UTC, clanmills commented
OK.  I'll say:
1) Exiv2 v0.27 can be built with VS 2008, 2010, 2012, 2013, 2015 and 2017.
2) Exiv2 v0.27.1 (and later) can be built with VS 2015, 2017 and 2019.
3) v0.28 is being "modernised" to C++11 and will not support C++98.  We don't expect Exiv2 v0.28 to build with VS 2008, 2010, 2012 or 2013.

I don't think we need CI for VS2019 at the moment.  This can be introduced for branch 'master' when AppVeyor supports VS2019.  I'll work with Nehal on Jenkins for branch '0.27-maintenance' and support 2015, 2017 and 2019.

2019-04-19 06:02 UTC, nehaljwani commented
Azure pipelines do support VS 2019 (preview), according to https://devblogs.microsoft.com/devops/hosted-pipelines-announcements-vs-2019-mojave-and-more/

Not saying that we should shift, just FYI.

2019-04-21 05:36 UTC, piponazo submitted a review, later dismissed

2019-04-22 22:02 UTC, D4N reviewed
Should we tag the last commit then as `0.27.1`?

2019-04-23 13:42 UTC, piponazo commented
> Should we tag the last commit then as 0.27.1?

How we did it the last time was:

1. Merge PR into 0.27-maintenance.
2. Tag the latest commit in 0.27-maintenance.

Otherwise, we could tag a commit and then continue working in the branch without it being merged. Right now the PR is blocked because you requested changes.

2019-04-23 14:18 UTC, D4N submitted a review, later dismissed
Let's get this release out!

2019-04-23 15:37 UTC, clanmills commented
The release will go out tomorrow _(assuming I don't find a show stopper)_.  Great work by lots of folks.  I'm humbled to be working with such talented and professional people.  Well done, everybody.

2019-04-25 18:44 UTC, piponazo approved these changes

2019-04-25 20:18 UTC, merged