Simplify strError tests to avoid differencies between platforms
Exiv2/exiv2 pull request #802
Opened 2019-04-27 12:41 UTC by piponazo

This PR fixes #763 .

I simplified the tests for `strError` so that we do not need to write complex if-else preprocessor conditions to check the slightly different messages in every platform.

2019-04-27 12:56 UTC, D4N commented
Lgtm, but gitlab is unhappy

2019-04-27 13:06 UTC, piponazo commented
Damn it ... gmock is not available in some of the Gitlab distros. I'll work to bring it. I expect to use GMock to mock some classes in the future.

2019-04-28 06:20 UTC, clanmills commented
You may (or may not) find my notes helpful:  https://github.com/Exiv2/exiv2/issues/575

2019-04-28 06:40 UTC, D4N commented
I've tried adding gmock in via 38b8ad7, let's see whether that works.

2019-04-29 02:38 UTC, nehaljwani commented on ci/install_dependencies.sh
> +        apt-get install -y cmake g++ clang make ccache python3 libexpat1-dev zlib1g-dev libssh-dev libcurl4-openssl-dev libgtest-dev libgmock-dev libxml2-utils
```suggestion
        apt-get install -y cmake g++ clang make ccache python3 libexpat1-dev zlib1g-dev libssh-dev libcurl4-openssl-dev googletest libxml2-utils
```
The new package name is just: googletest
```
root@7fbc3ab1d982:/# cat /etc/issue 
Debian GNU/Linux 9 \n \l

root@7fbc3ab1d982:/# apt-file search gmock/gmock.h
googletest: /usr/include/gmock/gmock.h
googletest: /usr/src/googletest/googlemock/include/gmock/gmock.h

root@7fbc3ab1d982:/# apt-file search gtest/gtest.h
googletest: /usr/include/gtest/gtest.h
googletest: /usr/src/googletest/googletest/include/gtest/gtest.h
```

2019-04-29 02:39 UTC, nehaljwani commented on ci/install_dependencies.sh
> +        echo "deb http://deb.debian.org/debian stretch-backports main contrib non-free" >> /etc/apt/sources.list
```suggestion
```

2019-04-29 03:42 UTC, nehaljwani commented
CI is happy now!

2019-04-29 05:59 UTC, piponazo commented
Now, I only need an approval! 😇

2019-04-29 09:19 UTC, D4N requested changes
I'll cleanup the commit log, then I'll approve.

2019-04-29 11:34 UTC, D4N approved these changes

2019-04-29 13:17 UTC, merged