Complete implementation of PNG IHDRC chunk decoding
Exiv2/exiv2 pull request #807
Opened 2019-04-28 08:16 UTC by piponazo

I started digging into the PNG specification and I will create few PRs dedicated to improve the decoding of PNG chunks. 

In this first PR I just focus on the [IHDR chunk](http://www.libpng.org/pub/png/spec/1.2/png-1.2-pdg.html#C.IHDR). We were only reading the width and height values from there and ignoring the rest of values. Now we read all the fields and we do the pertinent checks on their values. This should make the code more robust against malicious handmade PNG files. 

I also took the opportunity to continue updating the doxygen style and clang-format the files touched. 

Recommendation: review commit by commit.

2019-04-29 13:38 UTC, D4N commented
@piponazo Could you rebase this on master so that we get a coverage report?

2019-04-29 13:41 UTC, piponazo commented
> @piponazo Could you rebase this on master so that we get a coverage report?

done

2019-05-02 11:33 UTC, clanmills reviewed
This looks like a good overhaul of the PNG code.  And that's a good thing.  Thanks for digging around in that.

I am concerned about the symbol EXV_HAVE_PNG as that implies we are using libpng.  Perhaps EXV_ENABLE_PNG is a better name which (based on EXIV2_ENABLE_PNG in CMakeLists.txt).

For that matter, perhaps it's worthwhile replacing EXV_this_that with EXIV2_this_that.

2019-05-02 12:39 UTC, piponazo commented
> I am concerned about the symbol EXV_HAVE_PNG as that implies we are using libpng. Perhaps EXV_ENABLE_PNG is a better name which (based on EXIV2_ENABLE_PNG in CMakeLists.txt). For that matter, perhaps it's worthwhile replacing EXV_this_that with EXIV2_this_that.

I totally agree with you. I'll make both changes 😉

2019-05-02 15:33 UTC, D4N requested changes
I've added some nagging to the documentation, but unfortunately realized too late that you only reformated most of the doc comments, so feel free to ignore the "please clarify this" comments, unless you're highly motivated to address them :wink:.

I'd suggest to throw `kerFailedToReadMetadata` from the function that you completed, for consistency with the other png reading functions (that would also make the changes in the system test obsolete).

2019-05-02 15:33 UTC, D4N commented on src/pngchunk_int.hpp
> +            /// chunk data + CRC) as a string.
```suggestion
            ///     chunk data + CRC) as a string.
```

2019-05-02 17:30 UTC, piponazo commented on include/exiv2/pngimage.hpp
> +        /// \b Important: The constructor takes ownership of the passed in BasicIo instance through the auto-pointer.
I agree, I saw some of these comments and I actually simplified them (not sure if it was done in this PR or in other).

2019-05-02 17:32 UTC, piponazo commented on include/exiv2/pngimage.hpp
> -          @brief Print out the structure of image file.
It is exactly the same comment that comes from the Base class (**Image**). In Doxygen, there is documentation inheritance :smile_cat:

2019-05-02 17:32 UTC, piponazo commented on src/pngchunk_int.hpp
> +            /// @brief Parse PNG chunk contents to extract metadata container and assign it to image.
I'll try to do it when I write unit tests for it in the future :wink:

2019-05-02 17:45 UTC, piponazo commented
> I'd suggest to throw kerFailedToReadMetadata from the function that you completed, for consistency with the other png reading functions (that would also make the changes in the system test obsolete).

I am happy to apply this change, although the truth is that there is an existing mix in that file of exceptions: `kerFailedToReadImageData` and `kerCorruptedMetadata`. Do you know the difference between those 2 values ? When we should use one or the other ? In case there is not so much difference I would vote for removing one of them (In another PR).

2019-05-02 17:46 UTC, piponazo commented
> For that matter, perhaps it's worthwhile replacing EXV_this_that with EXIV2_this_that.

@clanmills I just replaced the definition I changed in this file. Since to do that change for all the definitions is a quite big task, I would prefer to do it in another PR.

2019-05-02 19:04 UTC, clanmills commented
Changing EXV_HAVE_PNG to EXIV2_ENABLE_PNG is the change I requested.

Changing all those EXV_ defines is something for another day.  We could ask Nehal to do that when everybody's on vacation (July?) and the change slides into the code without friction.

2019-05-02 19:24 UTC, D4N approved these changes

2019-05-02 19:26 UTC, D4N commented
> > I'd suggest to throw kerFailedToReadMetadata from the function that you completed, for consistency with the other png reading functions (that would also make the changes in the system test obsolete).
> 
> I am happy to apply this change, although the truth is that there is an existing mix in that file of exceptions: `kerFailedToReadImageData` and `kerCorruptedMetadata`. Do you know the difference between those 2 values ? When we should use one or the other ? In case there is not so much difference I would vote for removing one of them (In another PR).

I think `kerFailedToReadImageData` existed a long time before `kerCorruptedMetadata`, which I might have added when I just started contributing ("back then" we just had error codes and no enum for the numbers, so new errors got added left right and center, see #323)

2019-05-04 13:39 UTC, merged