Replace DEBUG with EXIV2_DEBUG_MESSAGES
Exiv2/exiv2 pull request #939
Opened 2019-06-28 17:41 UTC by piponazo

Fixes #926

Same than #938 but for master. Note that we might end up not merging this change into 0.27-maintenance

2019-07-07 19:22 UTC, D4N requested changes
LGTM, I've flagged two small inconsistencies in the docs.

2019-07-07 19:22 UTC, D4N commented on src/pngimage.cpp
> +        // str & length should compile time constants => only running this in EXIV2_DEBUG_MESSAGES mode is ok
This comment is wrong now.

2019-07-07 19:22 UTC, D4N commented on README.md
> +#ifdef EXIV2_DEBUG_MESSAGESDEBUG
The preprocessor symbol name is wrong and it doesn't make sense given the next paragraph which statest that this is "not compiled for debug builds".

This paragraph should imho instead explain that this preprocessor symbol is for debug messages.

2019-07-08 13:55 UTC, piponazo commented
@D4N I have addressed the two comments you've made. Let me know if you are happy with the new version 😉

2019-07-08 18:18 UTC, D4N approved these changes

2019-07-08 18:18 UTC, merged

2019-07-08 19:15 UTC, emmenlau commented
Awesome, thanks!