Add bounds check to MemIo::seek().
Exiv2/exiv2 pull request #944
Opened 2019-07-03 14:26 UTC by kevinbackhouse

Quick fix for bug reported in #943.

2019-07-03 19:41 UTC, D4N commented
@kevinbackhouse Thanks for the quick fix, the changes look good to me. Would you mind adding a unit test that detects regressions in this behavior?

2019-07-03 20:03 UTC, kevinbackhouse commented
Yes, I'll add a test.
I was also thinking that it might be a good idea to add an error flag to `MemIo::Impl`, so that we can implement `MemIo::error()` properly. A lot of the clients of this class call `error()` immediately after `seek()` to check if anything went wrong. Right now, `MemIo::error()` always returns 0.

2019-07-05 11:18 UTC, kevinbackhouse commented
I added a unit test. I also changed the bug fix so that it sets the `eof_` flag when you seek out of bounds. I decided against adding an error flag because I am not sure what it would mean.

2019-07-09 20:49 UTC, piponazo submitted a review, later dismissed
Thanks a lot for your contributions!

I left two minor suggestions but I am happy with the PR and we could merge it as it is.

2019-07-09 20:49 UTC, piponazo commented on unitTests/test_basicio.cpp
> +#include <cmath>
[minor] These headers seem to not be needed, right?. The only usage from standard functions that I see is `memset` which would be available in `#include <cstring>`

2019-07-09 20:49 UTC, piponazo commented on unitTests/test_basicio.cpp
> +    // Reset the file.
[suggestion] It seems that every time you are resetting, your aim is to make a slightly different test/check. I would propose to create different tests for each case, and try to give meaningful names to each of them.

If that's not the case or you prefer to not make more changes here let me know.

2019-07-10 20:57 UTC, D4N reviewed
The changes look good to me, thanks @kevinbackhouse!

Concerning the unit test: I'd prefer to move these into separate functions and to use a fixture for the `MemIo` initialization.

2019-07-11 07:53 UTC, D4N requested changes
Please mention CVE-2019-13504 in the commit log, in case anyone wants to cherry-pick fix.

2019-07-14 11:07 UTC, clanmills commented
It would be good to get this into 0.27.2.3 (RC3).  To do this, it has be in 0.27-maintenance today (2019-07-14), otherwise it'll have to wait for 0.27.3 (scheduled 2019-09-30).

2019-07-15 04:23 UTC, piponazo approved these changes

2019-07-15 11:51 UTC, D4N approved these changes

2019-07-15 12:30 UTC, merged